name: Elliot Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - closed
      - synchronize

jobs:
  job-1:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"

      - run: |
          echo "Hi Elliot"

      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
            echo "$GITHUB_CONTEXT"

      - name: If PR is closed
        if: ${{ github.event.pull_request.state == 'closed' }}
        run: echo "I was ran because the PR was closed"

      - name: If merge to main
        if: ${{ github.ref_name == 'main' }}
        run: echo "I was ran because of a merge to main"

      - name: PR Merge me
        if: ${{ github.event.pull_request.merged }}
        run: echo "I was merged because of github.event.pull_request.merged"