name: Elliot Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - closed
      - synchronize

jobs:
  job-1:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"

      - run: |
          echo "Hi Elliot"

      - name: Merge me
        if: ${{ github.ref_name == 'main' }}
        run: echo "I was merged because of a merge to main"

      - name: PR Merge me
        if: ${{ github.event.pull_request.merged }}
        run: echo "I was merged because of github.event.pull_request.merged"

      - name: PR was closed
        if: ${{ github.event.pull_request.closed }}
        run: echo "I was ran because the PR was closed"