name: Elliot Workflow

on:
  push:
    branches:
      - '**'
    tags:
      - v*
      - test*
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - closed
      - synchronize

env:
  FAROS_DRY_RUN: 1

jobs:
  job-1:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"

      - run: |
          echo "Hi Elliot"

      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
            echo "$GITHUB_CONTEXT"

      - name: If PR is closed
        if: ${{ github.event.pull_request.state == 'closed' && startsWith(github.event.pull_request.title, '[Merged By Bors]') }}
        run: echo "I was ran because the PR was closed and it was merged by BORS"

      - name: If merge to main
        if: ${{ github.ref_name == 'main' }}
        run: echo "I was ran because of a merge to main"

      - name: PR Merge me
        if: ${{ github.event.pull_request.merged }}
        run: echo "I was merged because of github.event.pull_request.merged"

      - run: |
          echo ${{ env.FAROS_DRY_RUN }}

      - run: |
          echo "FAROS_DRY_RUN=0" >> $GITHUB_ENV

      - run: |
          echo ${{ env.FAROS_DRY_RUN }}

      - run: |
          echo "$GITHUB_ENV"

  job-2:
    name: World
    runs-on: ubuntu-latest
    needs: [job-1]
    env:
      FAROS_DRY_RUN: ${{ (github.event.pull_request.merged || startsWith(github.ref_name, 'test')) && '0' || '1' }}
    steps:
      - run: |
          echo ${{ env.FAROS_DRY_RUN }}
