name: Elliot Workflow

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - '**'

jobs:
  job-1:
    name: Hello
    runs-on: ubuntu
    steps:
      - run: |
          echo "Hello World"

      - run: |
          echo "Hi Elliot"
  job-2:
    name: Merge Test
    runs-on: ubuntu
    if: ${{ github.event.pull_request.merged }}
    steps:
      - run: |
          echo "I was ran and merged"